//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Atividade_Realizada
    {
        public int Codigo { get; set; }
        public Nullable<int> Atividade { get; set; }
        public Nullable<int> Aluno { get; set; }
        public Nullable<int> Turma { get; set; }
        public string Matricula { get; set; }
        public Nullable<System.DateTime> DtInscricao { get; set; }
        public Nullable<System.DateTime> DtAceite { get; set; }
        public Nullable<System.DateTime> DtDevolucao { get; set; }
        public string Responsavel { get; set; }
        public string Observacao { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<int> HorasAtr { get; set; }
    }
}
