//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Bloqueio
    {
        public int Codigo { get; set; }
        public Nullable<int> Turma { get; set; }
        public Nullable<int> Aluno { get; set; }
        public Nullable<int> Coordenador { get; set; }
        public Nullable<System.DateTime> DtBloqueio { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
