//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Instituto
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public Nullable<System.DateTime> DtCriacao { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
