//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_VisaoAlunos
    {
        public int Codigo { get; set; }
        public Nullable<int> Controle { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<System.DateTime> DtCriacao { get; set; }
        public bool AvisoInsc { get; set; }
        public bool Status { get; set; }
        public string Email { get; set; }
        public bool Nota { get; set; }
        public bool HorasAtr { get; set; }
    }
}
