//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas_a_emitir
    {
        public int NumAlerta { get; set; }
        public string CodDisc { get; set; }
        public int NumProf { get; set; }
        public bool TipoAlerta { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public Nullable<System.DateTime> DtEfetivacao { get; set; }
        public bool Status { get; set; }
        public string DescMaterial { get; set; }
        public int QtdeAlertas { get; set; }
        public int QtdeLidos { get; set; }
    }
}
