//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alivre_ctrl_session
    {
        public System.Guid ssId { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Sessao { get; set; }
    }
}
