//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campanha
    {
        public int Codigo { get; set; }
        public System.DateTime DtInicio { get; set; }
        public System.DateTime DtFim { get; set; }
        public short Formato { get; set; }
        public string UrlImagem { get; set; }
        public string UrlDestino { get; set; }
        public string Descricao { get; set; }
        public int QtdExibMax { get; set; }
        public int QtdExib { get; set; }
        public int QtdClick { get; set; }
        public short WidImg { get; set; }
        public short HeiImg { get; set; }
        public string AltImg { get; set; }
        public int Chave { get; set; }
        public Nullable<short> Peso { get; set; }
    }
}
