//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        public Campus()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public short NumInstituicao { get; set; }


        public short NumCampus { get; set; }
        public string NomeCampus { get; set; }
    
        public virtual Instituicao Instituicao { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
