//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public short NumInstituicao { get; set; }
        public short NumCampus { get; set; }
        public short NumCurso { get; set; }
        public short NumTurma { get; set; }
        public short NumDisciplina { get; set; }
        public string NomeDisciplina { get; set; }
        public Nullable<int> NumProfessor { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual Turma Turma { get; set; }
    }
}
