//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disc_Aluno
    {
        public int NumInscricao { get; set; }
        public string CodDisc { get; set; }
        public int CodUsuario { get; set; }
        public System.DateTime DtInclusao { get; set; }
        public Nullable<System.DateTime> DtExclusao { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> AceitaRede { get; set; }
    }
}
