//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int Chave { get; set; }
        public int CodUsuario { get; set; }
        public int CodTexto { get; set; }
        public System.DateTime DtDownload { get; set; }
    }
}
