//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaleConosco
    {
        public int NumMensagem { get; set; }
        public Nullable<int> NumUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string EmailUsuario { get; set; }
        public string CidadeMensagem { get; set; }
        public string UFMensagem { get; set; }
        public string BairroMensagem { get; set; }
        public string IpMensagem { get; set; }
        public string TxtMensagem { get; set; }
        public Nullable<System.DateTime> DtMensagem { get; set; }
        public Nullable<bool> AceitaEmail { get; set; }
        public Nullable<bool> JaResp { get; set; }
    }
}
