//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumProfMsg
    {
        public int Num_Msg { get; set; }
        public int Num_Forum { get; set; }
        public System.DateTime Dta_Msg { get; set; }
        public int Aut_Msg { get; set; }
        public Nullable<bool> Sta_Msg { get; set; }
        public Nullable<bool> Flag_Msg { get; set; }
        public string Tit_Msg { get; set; }
        public string Txt_Msg { get; set; }
        public Nullable<int> Pai_Msg { get; set; }
    }
}
