//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumProfInsc
    {
        public int Num_Insc { get; set; }
        public int Num_Forum { get; set; }
        public int Num_Usuario { get; set; }
        public System.DateTime Dta_Insc { get; set; }
        public Nullable<System.DateTime> Dta_Aceite { get; set; }
        public Nullable<System.DateTime> Dta_Acesso { get; set; }
        public Nullable<System.DateTime> Dta_Exclusao { get; set; }
        public string Com_Insc { get; set; }
        public string Com_Aceite { get; set; }
        public short Sta_Insc { get; set; }
        public bool Aviso_Insc { get; set; }
    }
}
