//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumProf
    {
        public int Num_Forum { get; set; }
        public Nullable<int> Num_Prof { get; set; }
        public Nullable<System.DateTime> Dta_Criacao { get; set; }
        public Nullable<bool> PvtL_Forum { get; set; }
        public Nullable<bool> PvtP_Forum { get; set; }
        public Nullable<bool> Sta_Forum { get; set; }
        public string Tit_Forum { get; set; }
        public string Txt_Forum { get; set; }
        public Nullable<System.DateTime> Dta_Valid { get; set; }
    }
}
