//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndLivro
    {
        public int NumIndLivro { get; set; }
        public Nullable<int> ProfIndLivro { get; set; }
        public string TitIndLivro { get; set; }
        public string AutIndLivro { get; set; }
        public string ComIndLivro { get; set; }
        public Nullable<System.DateTime> DtIndLivro { get; set; }
        public Nullable<bool> StatIndLivro { get; set; }
    }
}
