//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscrEvento
    {
        public int NumInscr { get; set; }
        public int NumEvento { get; set; }
        public string Nome { get; set; }
        public bool Sexo { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public Nullable<System.DateTime> DtPagto { get; set; }
        public Nullable<decimal> VlrPagto { get; set; }
        public Nullable<System.DateTime> DtInscricao { get; set; }
    }
}
