//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituicao
    {
        public Instituicao()
        {
            this.Campus = new HashSet<Campus>();
        }
    
        public short NumInstituicao { get; set; }
        public string NomeInstituicao { get; set; }
        public string UfInstituicao { get; set; }
        public string CidInstituicao { get; set; }
    
        public virtual ICollection<Campus> Campus { get; set; }
    }
}
