//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int NumLink { get; set; }
        public string NomLink { get; set; }
        public string UrlLink { get; set; }
        public Nullable<int> QtdClick { get; set; }
        public Nullable<bool> TipLink { get; set; }
    }
}
