//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivroInd
    {
        public int Chave { get; set; }
        public Nullable<int> Num_Liv { get; set; }
        public Nullable<int> Num_Prof { get; set; }
        public Nullable<System.DateTime> Dta_Ind { get; set; }
        public string Com_Ind { get; set; }
        public Nullable<bool> Sta_Liv { get; set; }
    }
}
