//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int Num_Liv { get; set; }
        public string Tit_Liv { get; set; }
        public string Aut_Liv { get; set; }
        public string Edi_Liv { get; set; }
        public string Isb_Liv { get; set; }
        public Nullable<int> Ano_Liv { get; set; }
        public string Sin_Liv { get; set; }
        public string Url_Liv { get; set; }
        public string Img_Liv { get; set; }
        public string Cat_Liv { get; set; }
        public string Sub_Liv { get; set; }
        public Nullable<bool> Sta_Liv { get; set; }
    }
}
