//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitore
    {
        public int Chave { get; set; }
        public int Usuario { get; set; }
        public System.DateTime DtAcao { get; set; }
        public string Acao { get; set; }
        public bool Status { get; set; }
    }
}
