//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navegacao
    {
        public int NumNavegacao { get; set; }
        public Nullable<int> NumUsuario { get; set; }
        public string CodUsuario { get; set; }
        public Nullable<System.DateTime> DtNavegacao { get; set; }
        public string IpNavegacao { get; set; }
        public string PagNavegacao { get; set; }
    }
}
