//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLetter
    {
        public int Sequencia { get; set; }
        public Nullable<int> NumeroNews { get; set; }
        public Nullable<System.DateTime> DtMensagem { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Email { get; set; }
        public Nullable<bool> LeuEmail { get; set; }
        public Nullable<System.DateTime> DtLeitura { get; set; }
    }
}
