//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palestrante
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public bool Sexo { get; set; }
        public string Email { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public Nullable<int> Cep { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string MiniCV { get; set; }
    }
}
