//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parceiros
    {
        public System.Guid idParceiro { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> DtInclusao { get; set; }
        public Nullable<System.DateTime> DtInativacao { get; set; }
        public string UrlParceiro { get; set; }
        public string UrlImagemParc { get; set; }
        public Nullable<bool> LocalImagem { get; set; }
    }
}
