//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int NumPedido { get; set; }
        public Nullable<System.DateTime> DtPedido { get; set; }
        public string Produto { get; set; }
        public Nullable<int> Qtde { get; set; }
        public Nullable<decimal> VlrUnit { get; set; }
        public Nullable<decimal> VlrFrete { get; set; }
        public Nullable<decimal> VlrTotal { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Fone { get; set; }
    }
}
