//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesqUnip
    {
        public int Numero { get; set; }
        public Nullable<System.DateTime> DtResp { get; set; }
        public string Nome { get; set; }
        public string Fone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Campus { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Curso { get; set; }
        public Nullable<int> Situacao { get; set; }
        public Nullable<int> Resp02 { get; set; }
        public Nullable<int> Resp03 { get; set; }
        public Nullable<int> Resp04 { get; set; }
        public Nullable<int> Resp05 { get; set; }
        public Nullable<int> Resp06 { get; set; }
        public Nullable<int> Resp07 { get; set; }
        public string IpNum { get; set; }
    }
}
