//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texto
    {
        public int NumInstituicao { get; set; }
        public int NumCampus { get; set; }
        public int NumCurso { get; set; }
        public int NumTurma { get; set; }
        public int NumDisciplina { get; set; }
        public Nullable<int> NumTexto { get; set; }
        public int CodTexto { get; set; }
        public string NomeTexto { get; set; }
        public Nullable<System.DateTime> DtInclusao { get; set; }
        public Nullable<int> QtdeDownload { get; set; }
        public string UrlTexto { get; set; }
        public Nullable<int> TamTexto { get; set; }
        public Nullable<int> FormTexto { get; set; }
        public string SenhaTexto { get; set; }
        public Nullable<int> SitTexto { get; set; }
    }
}
