//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public Turma()
        {
            this.Disciplina = new HashSet<Disciplina>();
        }
    
        public short NumInstituicao { get; set; }
        public short NumCampus { get; set; }
        public short NumCurso { get; set; }
        public short NumTurma { get; set; }
        public string NomeTurma { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Disciplina> Disciplina { get; set; }
    }
}
