//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAlivre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFB
    {
        public int NumUsuario { get; set; }
        public string CodUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public byte SexoUsuario { get; set; }
        public string CidadeUsuario { get; set; }
        public string UFUsuario { get; set; }
        public Nullable<System.DateTime> DtNascUsuario { get; set; }
        public short TipoUsuario { get; set; }
        public System.DateTime DtIncUsuario { get; set; }
        public string IpIncUsuario { get; set; }
        public bool StatUsuario { get; set; }
        public Nullable<System.DateTime> DtExcUsuario { get; set; }
        public string IpExcUsuario { get; set; }
        public string SenhaUsuario { get; set; }
        public System.DateTime DtUltAcUsuario { get; set; }
        public Nullable<short> InstUsuario { get; set; }
        public Nullable<short> CampUsuario { get; set; }
        public string CursoUsuario { get; set; }
        public Nullable<short> TurnoUsuario { get; set; }
        public Nullable<short> PeriodoUsuario { get; set; }
        public Nullable<short> TipoPerUsuario { get; set; }
        public bool AceitaEmail { get; set; }
        public Nullable<short> DDDUsuario { get; set; }
        public string FoneUsuario { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public Nullable<bool> AceitaMkt { get; set; }
    }
}
